---
# Source: ping-pong/templates/ping_svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: de-918-ping-ehufagmnb-0-0-0-ping-pong-ping
  namespace: default
spec:
  selector:
    app: de-918-ping-ehufagmnb-0-0-0-ping-pong-ping
  type: NodePort
  ports:
    - protocol: TCP
      port: 18888
      targetPort: 18888
---
# Source: ping-pong/templates/pong_svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: de-918-ping-ehufagmnb-0-0-0-ping-pong-pong
  namespace: default
spec:
  selector:
    app: de-918-ping-ehufagmnb-0-0-0-ping-pong-pong
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 18889
      targetPort: 18889
---
# Source: ping-pong/templates/ping.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  de-918-ping-ehufagmnb-0-0-0-ping-pong-ping
  namespace: default
  labels:
    app: de-918-ping-ehufagmnb-0-0-0-ping-pong-ping

spec:
  replicas: 1
  selector:
    matchLabels:
      app: de-918-ping-ehufagmnb-0-0-0-ping-pong-ping
      release: de-918-ping-ehufagmnb-0-0-0

  template:
    metadata:
      labels:
        app: de-918-ping-ehufagmnb-0-0-0-ping-pong-ping
        release: de-918-ping-ehufagmnb-0-0-0
        network-service-id: 39dec755-7d9d-4441-869f-d6becba21bdf
        type: ping
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": "de-918-ping-ehufagmnb-0-0-0-ping-pong",
                                        "namespace": "default"}]'
        prometheus.io/scrape: "true"
        prometheus.io/path: /api/v1/ping/metrics
        prometheus.io/port: "18888"
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: network-service-id
                operator: In
                values:
                - 39dec755-7d9d-4441-869f-d6becba21bdf
              - key: type
                operator: In
                values:
                - pong
            topologyKey: kubernetes.io/hostname
      containers:
      - name: de-918-ping-ehufagmnb-0-0-0-ping-pong
        image: artifactory.riftio.com/docker/rw.ping:2004
        imagePullPolicy: IfNotPresent
---
# Source: ping-pong/templates/pong.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  de-918-ping-ehufagmnb-0-0-0-ping-pong-pong
  namespace: default
  labels:
    app: de-918-ping-ehufagmnb-0-0-0-ping-pong-pong

spec:
  replicas: 1
  selector:
    matchLabels:
      app: de-918-ping-ehufagmnb-0-0-0-ping-pong-pong
      release: de-918-ping-ehufagmnb-0-0-0

  template:
    metadata:
      labels:
        app: de-918-ping-ehufagmnb-0-0-0-ping-pong-pong
        release: de-918-ping-ehufagmnb-0-0-0
        network-service-id: 39dec755-7d9d-4441-869f-d6becba21bdf
        type: pong
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": "de-918-ping-ehufagmnb-0-0-0-ping-pong",
                                        "namespace": "default"}]'
        prometheus.io/scrape: "true"
        prometheus.io/path: /api/v1/pong/metrics
        prometheus.io/port: "18889"
    spec:
      containers:
      - name: de-918-ping-ehufagmnb-0-0-0-ping-pong
        image: artifactory.riftio.com/docker/rw.pong:2005
        imagePullPolicy: IfNotPresent
---
# Source: ping-pong/templates/network.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: de-918-ping-ehufagmnb-0-0-0-ping-pong
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "net1",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.234.0/24",
        "rangeStart": "192.168.234.200",
        "rangeEnd": "192.168.234.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.234.1"
      }
    }'
