{
 "title": "RW.Auth Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RW.Auth stats rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate (rw_auth_stats_total[3m])", "legendFormat": "{{stat_type}}" }
   ]
  },
  {
   "title": "RW.Auth current stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rw_auth_stats_total", "legendFormat": "{{stat_type}}" }
   ]
  },
  {
   "title": "Active auth sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rw_auth_active_sessions", "legendFormat": "active_sessions" }
   ]
  }
 ]
}