{
 "title": "RW.CaaS VIM Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "project", "query": "default" },
   { "name": "datacenter", "label": "datacenter", "query": "aws" }
  ]
 },
 "panels": [
  {
   "title": "Nodes in cluster",
   "type": "stat",
   "description": "Number of nodes in the K8s cluster",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_caas_nodes_in_cluster_count{datacenter=\"${datacenter}\", project=\"${project}\"}"
    }
   ]
  },
  {
   "title": "Pods In Use",
   "type": "stat",
   "description": "Number of Pods currently running in the datacenter",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_caas_pods_in_use_count{project=\"${project}\", datacenter=\"${datacenter}\"}"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "description": "Number of containers running in the cluster",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_caas_containers_in_use_count{datacenter=\"${datacenter}\"}"
    }
   ]
  },
  {
   "title": "Pod and Container usage over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rw_caas_pods_in_use_count{project=\"${project}\", datacenter=\"${datacenter}\"}",
     "legendFormat": "pod"
    },
    {
     "expr": "rw_caas_containers_in_use_count{project=\"${project}\", datacenter=\"${datacenter}\"}",
     "legendFormat": "container"
    }
   ]
  },
  {
   "title": "POD resource utilization (EKS Only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU usage by all Pods (Percent)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rw_caas_pod_cpu_usage_in_percent{project=\"${project}\", datacenter=\"${datacenter}\"})"
      }
     ]
    },
    {
     "title": "Total memory used by all Pods (Percent)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rw_caas_pod_memory_usage_in_percent{project=\"${project}\", datacenter=\"${datacenter}\"})"
      }
     ]
    },
    {
     "title": "Top 10 CPU consuming pods",
     "type": "graph",
     "description": "CPU consumption in percentage as reported by \"pod_cpu_utilization\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rw_caas_pod_cpu_usage_in_percent{project=\"${project}\", datacenter=\"${datacenter}\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Top 10 memory consuming pods",
     "type": "graph",
     "description": "Top 10 memory consuming pods in percent. As reported by \"pod_memory_utilization\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rw_caas_pod_memory_usage_in_percent{project=\"${project}\", datacenter=\"${datacenter}\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU/Memory Usage over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU/Cores usage in nodes",
   "type": "graph",
   "description": "CPU usage as in number of cores used",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rw_caas_node_cpu_usage_in_milli{project=\"${project}\", datacenter=\"${datacenter}\"} / 1000",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "graph",
   "description": "Memory used by the k8s nodes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "rw_caas_node_memory_usage_in_bytes{project=\"${project}\", datacenter=\"${datacenter}\"} / 1024 / 1024",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, rw_caas_container_memory_usage_in_bytes{project=\"${project}\", datacenter=\"${datacenter}\"}) / 1024 / 1024",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers CPU/Core usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rw_caas_container_cpu_usage_in_milli{project=\"${project}\", datacenter=\"${datacenter}\"}) / 1000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Capacity/Allocatable & Cluster Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Capacity Per Node",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rw_caas_node_memory_cumulative_in_bytes{project=\"${project}\", datacenter=\"${datacenter}\", type=\"capacity\"} / 1024 / 1024 / 1024",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Memory Allocatable Per Node",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rw_caas_node_memory_cumulative_in_bytes{project=\"${project}\", datacenter=\"${datacenter}\", type=\"allocatable\"} / 1024 / 1024 / 1024",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Allocatable/Capacity Memory (Cluster)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum without(node_name)(rw_caas_node_memory_cumulative_in_bytes{project=\"${project}\", datacenter=\"${datacenter}\"}) / 1024 / 1024 / 1024",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Memory Usage Percent (Cluster)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (rw_caas_node_memory_usage_in_bytes{project=\"${project}\", datacenter=\"${datacenter}\"}) / sum(rw_caas_node_memory_cumulative_in_bytes{project=\"${project}\", datacenter=\"${datacenter}\", type=\"allocatable\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Capacity/Allocatable & Cluster Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU/Cores Capacity Per Node",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rw_caas_node_cpu_cumulative_in_milli{project=\"${project}\", datacenter=\"${datacenter}\", type=\"capacity\"} / 1000",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "CPU/Core Allocateble Per Node",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rw_caas_node_cpu_cumulative_in_milli{project=\"${project}\", datacenter=\"${datacenter}\", type=\"allocatable\"} / 1000",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Cluster CPU/Core Allocatable/Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum without (node_name) (rw_caas_node_cpu_cumulative_in_milli{project=\"${project}\", datacenter=\"${datacenter}\"}) / 1000",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "CPU/Core Usage (Cluster)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (rw_caas_node_cpu_usage_in_milli{project=\"${project}\", datacenter=\"${datacenter}\"}) / sum(rw_caas_node_cpu_cumulative_in_milli{project=\"${project}\", datacenter=\"${datacenter}\", type=\"allocatable\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods Capacity/Allocatable & Cluster Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Capacity Per Node",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rw_caas_node_pod_cumulative_count{project=\"${project}\", datacenter=\"${datacenter}\", type=\"capacity\"}",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Allocatable Pods Per Node",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rw_caas_node_pod_cumulative_count{project=\"${project}\", datacenter=\"${datacenter}\", type=\"allocatable\"}",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Cluster Pod allocation/capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum without(node_name) (rw_caas_node_pod_cumulative_count{project=\"${project}\", datacenter=\"${datacenter}\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Pod Percentage Use (Cluster)",
     "type": "gauge",
     "description": "Percentage Pods in use percent w.r.t allowable pods in the cluster",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rw_caas_pods_in_use_count{project=\"${project}\", datacenter=\"${datacenter}\"}) / sum(rw_caas_node_pod_cumulative_count{project=\"${project}\", datacenter=\"${datacenter}\", type=\"allocatable\"}) * 100"
      }
     ]
    }
   ]
  }
 ]
}