{
 "title": "LP Core Metrics",
 "description": "Monitoring LP core container",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Node User CPU",
   "type": "gauge",
   "description": "User CPU usage of the node on which LP container is running.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_node_cpu_usage{lp_service=\"core\", type=\"user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Node System CPU",
   "type": "gauge",
   "description": "System CPU usage on the node where LP core container is running.",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_node_cpu_usage{lp_service=\"core\", type=\"system\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "stat",
   "description": "Memory used by the node on which LP container is running",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_node_memory_usage_mib{lp_service=\"core\"}"
    }
   ]
  },
  {
   "title": "Memory provisioned",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_lp_memory_total_mib{lp_service=\"core\"}"
    }
   ]
  },
  {
   "title": "Percentage RSS memory used",
   "type": "gauge",
   "description": "Percentage of RSS memory consumed by the LP service container.",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rw_lp_used_memory_mib{lp_service=\"core\", type=\"rss\"}) / sum(rw_lp_memory_total_mib{lp_service=\"core\"}) * 100"
    }
   ]
  },
  {
   "title": "RVR usage",
   "type": "gauge",
   "description": "Rift var root usage in percentage.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_lp_disk_usage{lp_service=\"core\", type=\"RVR\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top 5 USS users",
   "type": "graph",
   "description": "Top 5 processes running in LP core container using most USS memory",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk (5, rw_lp_memory_usage_mib{lp_service=\"core\", type=\"uss\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Top 5 VMZ users",
   "type": "graph",
   "description": "Top 5 VMZ memory users in LP core container.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk (5, rw_lp_memory_usage_mib{lp_service=\"core\", type=\"vmz\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Top 5 RSS users",
   "type": "graph",
   "description": "Top 5 processes consuming most RSS in LP core container.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk (5, rw_lp_memory_usage_mib{lp_service=\"core\", type=\"rss\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Top 5 CPU perc users",
   "type": "graph",
   "description": "Top 5 processes consuming CPU in LP core container.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk (5, rw_lp_cpu_usage{lp_service=\"core\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Top 5 file descriptor users",
   "type": "graph",
   "description": "Top 5 processes consuming file descriptors in LP core container.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk (5, rw_lp_file_descriptor_count{lp_service=\"core\", job=\"lp-exporter\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Top 5 thread users",
   "type": "graph",
   "description": "Top 5 thread users in LP core container.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk (5, rw_lp_thread_count{lp_service=\"core\", job=\"lp-exporter\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "LP container CPU usage",
   "type": "graph",
   "description": "CPU used by the container.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rw_lp_total_cpu_usage{lp_service=\"core\"}",
     "legendFormat": "{{lp_service}}"
    }
   ]
  },
  {
   "title": "LP CPU Usage by Process",
   "type": "graph",
   "description": "CPU usage for all processes running inside LP core container.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rw_lp_cpu_usage{lp_service=\"core\", job=\"lp-exporter\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "LP core memory usage",
   "type": "graph",
   "description": "RSS and Cached memory usage in the container.",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rw_lp_used_memory_mib{lp_service=\"core\", type=\"rss\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rw_lp_used_memory_mib{lp_service=\"core\", type=\"cached\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "VMZ LP Core Memory Usage",
   "type": "graph",
   "description": "Memory used by processes in LP core container.",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rw_lp_memory_usage_mib{lp_service=\"core\", job=\"lp-exporter\", type=\"vmz\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "RSS LP Core Memory Usage",
   "type": "graph",
   "description": "RSS memory used by processes running in LP core container.",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rw_lp_memory_usage_mib{lp_service=\"core\", job=\"lp-exporter\",type=\"rss\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "USS LP Core Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rw_lp_memory_usage_mib{lp_service=\"core\", type=\"uss\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Thread usage LP Core",
   "type": "graph",
   "description": "Thread usage by processes running on LP core container.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rw_lp_thread_count{lp_service=\"core\", job=\"lp-exporter\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "File descriptor Usage for LP Core",
   "type": "graph",
   "description": "File descriptor usage by processes running on LP core container.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rw_lp_file_descriptor_count{lp_service=\"core\", job=\"lp-exporter\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  }
 ]
}