{
 "title": "LP System Debugging",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx HTTP status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (count_over_time( {job=\"nginx\"} [1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Nginx Request Count by Status Code",
   "type": "bargauge",
   "description": "Count of requests processed with the corresponding status code within the provided time range",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"nginx\"}[$timeRange])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RW.Rest Error Log Rate",
   "type": "graph",
   "description": "Rate at which error logs are getting logged in Restconf.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({job=\"rw-rest\"} |= \"error\" [1m])) by (event_name)",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Nginx Error log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"nginx\", status !~ \"200|201|204\" }"
    }
   ]
  },
  {
   "title": "RW.Rest Error log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"rw-rest\"} |= \"error\""
    }
   ]
  },
  {
   "title": "Rift Log error rate",
   "type": "graph",
   "description": "Rate at which errors are getting logged in rift.log",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({job=\"rift-log\"} |= \"error\" [1m]))",
     "legendFormat": "error_count"
    }
   ]
  },
  {
   "title": "Rift Log Error",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{job=\"rift-log\"} |= \"error\""
    }
   ]
  },
  { "title": "MANO subsystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Rate of logs per serverity (lcm-worker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({job=\"lcm-worker\"}[1m])) by (severity)"
    }
   ]
  },
  {
   "title": "Rate of logs per serverity(lcm-config-worker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({job=\"lcm-config-worker\"}[1m])) by (severity)"
    }
   ]
  },
  {
   "title": "Error by component",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"lcm-worker\", severity=\"error\"}[$timeRange]))",
     "legendFormat": "{{lcm-worker}}"
    },
    {
     "expr": "sum(count_over_time({job=\"lcm-config-worker\", severity=\"error\"}[$timeRange]))",
     "legendFormat": "{{lcm-config-worker}}"
    }
   ]
  },
  {
   "title": "Count by event name",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"lcm-worker\"}[$timeRange])) by (event_name)",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "LCM Worker event rate by event name",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate({job=\"lcm-worker\"} [1m])) by (event_name)",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "LCM Config Worker event rate by event name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate({job=\"lcm-config-worker\"} [1m])) by (event_name)",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Rate of error log by event name",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({job=\"lcm-worker\", severity=\"error|warning\"}[1m])) by (job, event_name)",
     "legendFormat": "lcm-wroker - {{event_name}}"
    },
    {
     "expr": "sum(rate({job=\"lcm-config-worker\", severity=\"error|warning\"}[1m])) by (job, event_name)",
     "legendFormat": "lcm-config-worker - {{event_name}}"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "{job=~\"lcm-worker|lcm-config-worker|lcm-monitor\", severity=\"error\"}"
    }
   ]
  }
 ]
}