{
 "title": "RW.MANO Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Pods Deployed",
   "type": "gauge",
   "description": "Number of Pods currently deployed by RIFT.ware",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_lp_current_instantiation_count{type=\"pod\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current VMs Deployed",
   "type": "gauge",
   "description": "Numbers of VMs currently deployed by RIFT.ware",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_lp_current_instantiation_count{type=\"vm\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cumulative Pods Deployed",
   "type": "stat",
   "description": "Total number of Pods deployed by RIFT.ware till date",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_lp_cumulative_instantiation_total{type=\"pod\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cumulative VMs Deployed",
   "type": "stat",
   "description": "Total number of VMs deployed by RIFT.ware till date",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_lp_cumulative_instantiation_total{type=\"vm\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current NS assignment",
   "type": "bargauge",
   "description": "NSes assigned to LCM worker instances and LCM config worker instances.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rw_lcm_worker_ns_assignment)",
     "legendFormat": "lcm-worker"
    },
    {
     "expr": "sum (rw_lcm_config_worker_ns_assignment)",
     "legendFormat": "lcm-config-worker"
    }
   ]
  },
  {
   "title": "Cumulative NS assignment",
   "type": "bargauge",
   "description": "NSes assigned till now to LCM worker and LCM config worker instances till now.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rw_lcm_worker_cumulative_ns_assignment_total)",
     "legendFormat": "lcm-worker"
    },
    {
     "expr": "sum (rw_lcm_config_worker_cumulative_ns_assignment_total)",
     "legendFormat": "lcm-config-worker"
    }
   ]
  },
  {
   "title": "State of Workers (Manager PoV)",
   "type": "table",
   "description": "State of the Workers as seen form Manager",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rw_mano_worker_state{type=\"from_manager\"}",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  {
   "title": "State of Workers(Worker PoV)",
   "type": "table",
   "description": "State of the workers as per the worker op data",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rw_mano_worker_state{type=\"from_worker\"}",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  {
   "title": "LCM worker NS assignment rate",
   "type": "graph",
   "description": "Rate at which the NSes are getting assigned to LCM workers",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(rw_lcm_worker_cumulative_ns_assignment_total[3m])) by (worker_id)",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  {
   "title": "LCM Config worker NS assignment rate",
   "type": "graph",
   "description": "Rate at which the NSes are getting assigned to LCM config workers",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (rw_lcm_config_worker_cumulative_ns_assignment_total[3m])) by (worker_id)",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  {
   "title": "LCM Worker Queue consumption rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Instantiation queue task consumption derivative",
   "type": "graph",
   "description": "Rate at which tasks are being picked up and executed from the Instantiation queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(rw_lcm_worker_queue_size{type=\"instantiation_queue_size\"}[5m])",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  {
   "title": "Termination queue task consumption derivative",
   "type": "graph",
   "description": "Rate at which tasks are being picked up and executed from the Termination queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(rw_lcm_worker_queue_size{type=\"termination_queue_size\"}[5m])",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  { "title": "LCM Worker Queue Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "LCM Worker Instantiation Q size",
   "type": "gauge",
   "description": "Number of tasks pending in the LCM worker instantiation queues",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_lcm_worker_queue_size{type=\"instantiation_queue_size\"}",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  {
   "title": "LCM Worker Termination Q size",
   "type": "gauge",
   "description": "Number of tasks pending in the LCM worker termination queues",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_lcm_worker_queue_size{type=\"termination_queue_size\"}",
     "legendFormat": "{{worker_id}}"
    }
   ]
  }
 ]
}