{
 "title": "RW.Metric Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FD usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"metric-exporter\"}",
     "legendFormat": "process_open_fds"
    },
    {
     "expr": "process_max_fds{job=\"metric-exporter\"}",
     "legendFormat": "process_max_fds"
    }
   ]
  },
  {
   "title": "RSS usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"metric-exporter\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Failed poll rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum without(instance, job, path) (rate(http_poll_requests_latency_ms_count{code!='200'}[5m]))"
    }
   ]
  },
  {
   "title": "Success poll rate(RPS)",
   "type": "graph",
   "description": "Rate or requests per second at which poll is happening (only for succesfull poll).",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum without(instance, job, path) (rate(http_poll_requests_latency_ms_count{code='200'}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP  endpoints",
   "type": "graph",
   "description": "Number of endpoints being polled and monitored by the metric exporter.",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(http_poll_monitored_eps)" }
   ]
  },
  {
   "title": "HTTP poll latency(ms)",
   "type": "graph",
   "description": "Latency of successful HTTP queries made i.e response with result code as 200",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_poll_requests_latency_ms_sum[5m]) / rate(http_poll_requests_latency_ms_count[5m])"
    }
   ]
  },
  {
   "title": "Goroutine count",
   "type": "stat",
   "description": "Number of go routines currently being used by the exporter.",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"metric-exporter\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"metric-exporter\"}"
    }
   ]
  },
  {
   "title": "Metric Exporter | Heap Objects",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"metric-exporter\"}"
    }
   ]
  },
  {
   "title": "Metric export | Heap in-use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"metric-exporter\"}"
    }
   ]
  },
  {
   "title": "Goroutine usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"metric-exporter\"}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"metric-exporter\"}"
    }
   ]
  }
 ]
}