{
 "title": "RW.Rest Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Request Rate(RPS)",
   "type": "stat",
   "description": "Request rate across all RW.Rest workers over period of 1 minute.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_count[1m]))"
    }
   ]
  },
  {
   "title": "Average request latency",
   "type": "stat",
   "description": "Average request latency across all RW.Rest workers ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum[3m])) / sum (rate(rw_rest_request_latency_ms_count[3m]))"
    }
   ]
  },
  {
   "title": "Total requests processed by Method",
   "type": "stat",
   "description": "Total requests processed by all RW.Rest workers. Includes success and failure",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (code, handler, job) (rw_rest_request_latency_ms_count)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "5xx/4xx Error response rate",
   "type": "graph",
   "description": "Rate at which requests are getting sent with HTTP status code 5xx or 4xx",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_count{code=~\"5.*|4.*\"}[1m])) by (code)",
     "legendFormat": "{{code}} {{job}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "description": "Request rate at which Rest workers are processing. This includes both proxied and non proxied requests.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (rw_rest_request_latency_ms_count[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request rate for backend (non proxy)",
   "type": "graph",
   "description": "Rate for requests which are sent to back-end via management agent. Does not involve any proxy queries.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (code, job) (rate (rw_rest_request_latency_ms_count{handler=\"http_handler\"}[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Average request latency",
   "type": "graph",
   "description": "Average request latency for both backend (non-proxy) and proxy requests taken together.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum{method=\"GET\"}[1m])) / sum (rate(rw_rest_request_latency_ms_count{method=\"GET\"}[1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum{method=\"POST\"}[1m])) / sum (rate(rw_rest_request_latency_ms_count{method=\"POST\"}[1m]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum{method=\"PUT\"}[1m])) / sum (rate(rw_rest_request_latency_ms_count{method=\"PUT\"}[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum{method=\"DELETE\"}[1m])) / sum (rate(rw_rest_request_latency_ms_count{method=\"DELETE\"}[1m]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Average backend request latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum{handler=\"http_handler\", method=\"GET\"}[1m])) / sum (rate(rw_rest_request_latency_ms_count{handler=\"http_handler\", method=\"GET\"}[1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum{handler=\"http_handler\", method=\"POST\"}[1m])) / sum (rate(rw_rest_request_latency_ms_count{handler=\"http_handler\", method=\"POST\"}[1m]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum{handler=\"http_handler\", method=\"PUT\"}[1m])) / sum (rate(rw_rest_request_latency_ms_count{handler=\"http_handler\", method=\"PUT\"}[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum (rate(rw_rest_request_latency_ms_sum{handler=\"http_handler\", method=\"DELETE\"}[1m])) / sum (rate(rw_rest_request_latency_ms_count{handler=\"http_handler\", method=\"DELETE\"}[1m]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Restconf-8016",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests processed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (code, handler, job) (rw_rest_request_latency_ms_count{job=\"rw-rest-8016\"})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Error response accum",
     "type": "graph",
     "description": "Error responses seen by this RW.Rest worker",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rw_rest_request_latency_ms_count{job=\"rw-rest-8016\", code=~\"5.*|4.*\"}",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  },
  { "title": "Restconf-8017", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Requests processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (code, handler, job) (rw_rest_request_latency_ms_count{job=\"rw-rest-8017\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error response accum",
   "type": "graph",
   "description": "Error responses seen by this RW.Rest worker",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rw_rest_request_latency_ms_count{job=\"rw-rest-8017\", code=~\"5.*|4.*\"}) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Restconf-8018",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests processed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (code, handler, job) (rw_rest_request_latency_ms_count{job=\"rw-rest-8018\"})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Error response accum",
     "type": "graph",
     "description": "Error responses seen by this RW.Rest worker",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rw_rest_request_latency_ms_count{job=\"rw-rest-8018\", code=~\"5.*|4.*\"}",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  }
 ]
}