{
 "title": "RW.EventsDB Metrics",
 "description": "MongoDB Prometheus Exporter Dashboard. \r\nWorks well with https://github.com/dcu/mongodb_exporter\r\n\r\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.\r\n\r\nThis is an updated version from https://grafana.com/grafana/dashboards/2583. \r\n\r\nApplicable to Mongo 4.28.\r\n\r\nTested with https://bitnami.com/stack/mongodb/helm",
 "tags": [ "prometheus" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "label_values(mongodb_connections, instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\", engine=\"wiredTiger\"}, instance)"
   },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "WiredTiger Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "env" },
  {
   "title": "WiredTiger Cache Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=~\"$host\", type=\"total\"}"
    }
   ]
  },
  {
   "title": "WiredTiger Max Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=~\"$host\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"delete\"}[5m])",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"update\"}[5m])",
     "legendFormat": "repl_updated"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"insert\"}[5m])",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$host\"}[5m])",
     "legendFormat": "ttl_deleted"
    }
   ]
  },
  {
   "title": "WiredTiger Log Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_operations_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_operations_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=~\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Health metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=~\"$env\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$env\",state=\"available\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$env\",state=\"current\"}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_oplog_size_bytes{instance=~\"$env\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$env\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Oplog Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_replset_oplog_head_timestamp[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_ms{instance=~\"shr.*\"}[5m])/1000 or irate(node_disk_io_time_ms{instance=~\"shr.*\"}[5m])/1000)",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  }
 ]
}